language: cpp
compiler:
  - gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libqt4-dev build-essential
 - wget http://www.xsquawkbox.net/xpsdk/XPSDK212.zip
 - unzip *.zip
 - qmake
script: make
branches:
  only:
    - master
notifications:
  recipients:
    - ville.ranki@iki.fi
  email:
    on_success: change
    on_failure: always

